# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stage whisper
email: gergo.sulymosi@gmail.com
description: Intended to be overheard.
domain: trekdemo.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trekdemo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Theme SoSimple
# https://github.com/mmistakes/so-simple-theme/blob/master/_config.yml
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"

permalink: /:title
markdown: kramdown
feed:
  path: atom.xml

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name: Gergő Sulymosi
  # picture:
  email: gergo.sulymosi@gmail.com
  twitter: trekdemo
  # links:
  #   - title: GitHub
  #     url: https://github.com/trekdemo
  #     icon: fas fa-rss-square

# Footer Links
footer_links:
  - title: Instagram
    url: https://instagram.com/trekdemo
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/trekdemo
    icon: fab fa-github-square
  - title: Twitter
    url: https://twitter.com/trekdemo
    icon: fab fa-twitter-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
